version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - IS_DOCKER=true
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=property_user
      - POSTGRES_PASSWORD=property_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
